void emoba() {
	FILE *archivo;
	archivo = fopen("El modelo basado en la disposición de electrones en niveles sucesivos. Concepto de orbital. Los números cuánticos.doc","w");
	if(archivo == NULL) {
		p("No se ha podido abrir el archivo.\n\n");
	}
	
	p("El modelo basado en la disposici%cn de electrones en niveles sucesivos. Concepto de orbital. Los n%cmeros cu%cnticos. Notaci%cn de los orbitales y configuraci%cn electr%cnica. Tabla peri%cdica de los elementos y su interpretaci%cn electr%cnica:\n",162,163,160,162,162,162,162,162,162);
	p("===========================================================================================================================================================================================================================================\n\n");
	p("- Configuraci%cn electr%cnica:\n",162,162);
	p("----------------------------\n\n");
	p("En qu%cmica, la configuraci%cn electr%cnica indica la manera en la cual los electrones se estructuran, comunican u organizan en un %ctomo de acuerdo con el modelo de capas electr%cnicas, en el cual las funciones de ondas del sistema se expresan como un %ctomo o at%cmicamente un producto de orbitales antisimetrizadas. La configuraci%cn electr%cnica es importante ya que determina las propiedades de combinaci%cn qu%cmica de los %ctomos y por lo tanto su posici%cn en la tabla peri%cdica de los elementos.\n\n",161,162,162,160,162,160,162,162,162,162,161,160,162,162);
	
	system("pause");
	p("\n");
	
	p(" - Introducci%cn:\n\n",162);
	p(" La disposici%cn de los electrones en los %ctomos est%c sujeta a las reglas de la mec%cnica cu%cntica. En particular la configuraci%cn electr%cnica viene dada por una combinaci%cn de estados cu%cnticos que son soluci%cn de la ecuaci%cn de Schr%cdinger para dicho %ctomo.\n\n",162,160,160,160,160,162,162,162,160,162,162,148,160);
	p(" Una de las restricciones de la mec%cnica cu%cntica no expl%ccitamente metida en la ecuaci%cn de Schr%cdinger es que cualquier conjunto de electrones en un mismo estado cu%cntico deben cumplir el principio de exclusi%cn de Pauli por ser fermiones (part%cculas de esp%cn semientero). Dicho principio implica que la funci%cn de onda total que describe dicho conjunto de electrones debe ser antisim%ctrica. Por lo tanto, en el momento en que un estado cu%cntico es ocupado por un electr%cn, el siguiente electr%cn debe ocupar un estado cu%cntico diferente.\n\n",160,160,161,162,148,160,162,161,161,162,130,160,162,162,160);
	p(" En los estados estacionarios de un %ctomo, la funci%cn de onda de un electr%cn en una aproximaci%cn no-relativista los estados que son funci%cn propia de la ecuaci%cn de Schr%cdinger es el hamiltoniano monoelectr%cnico correspondiente. Para el caso relativista hay que recurrir a la ecuaci%cn de Dirac. Las funciones propias obtenidas como soluci%cn de cualquiera de estas dos estaciones se denominan orbitales at%cmicos, por analog%ca con la imagen cl%csica de electrones orbitando alrededor del n%ccleo. Estos orbitales, en su expresi%cn m%cs b%csica, se pueden enumerar mediante cuatro n%cmeros cu%cnticos: n, l, ml y ms. Obviamente, el principio de exclusi%cn de Pauli implica que no puede haber dos electrones en un mismo %ctomo con los cuatro valores de los n%cmeros cu%cnticos iguales (porque entonces ocupar%can el mismo orbital y eso est%c excluido por el principio).\n\n",160,162,162,162,162,162,148,162,162,162,162,161,160,163,162,160,160,163,160,162,160,163,160,161,160);
	p(" De acuerdo con la mec%cnica cu%cntica, los electrones pueden pasar de un orbital at%cmico a otro ya sea emitiendo o absorbiendo un cuanto de energ%ca, en forma de fot%cn. Esta transici%cn de un orbital a otro con diferentes energ%cas explican diversos fen%cmenos de emisi%cn y absorci%cn de radiaci%cn electromagn%ctica por parte de los %ctomos.\n\n",160,160,162,161,162,162,161,162,162,162,162,130,160);
	
	system("pause");
	p("\n");
	
	p(" - Notaci%cn:\n\n",162);
	p(" Se utiliza en una notaci%cn est%cndar para describir las configuraciones electr%cnicas de %ctomos y mol%cculas. Para los %ctomos, la notaci%cn contiene la definici%cn de los orbitales at%cmicos (en la forma n l, por ejemplo 1s, 2p, 3d, 4f) indicando el n%cmero de electrones asignado a cada orbital (o al conjunto de orbitales de la misma subcapa) como un super%cndice. Por ejemplo, el hidr%cgeno tiene un electr%cn en el orbital s de la primera capa, de ah%c que su configuraci%cn electr%cnica se escriba 1s1. El litio tiene dos electrones en la subcapa 1s y uno en la subcapa 2s (de mayor energ%ca), de ah%c que su configuraci%cn electr%cnica se escriba 1s2 2s1 (pronunci%cndose 'uno-ese-dos, dos-ese-uno'). Para el f%csforo (n%cmero at%cmico 15), tenemos: 1s2 2s2 2p6 3s2 3p3.\n\n",162,160,162,160,130,160,162,162,162,163,161,162,162,161,162,162,161,161,162,162,160,162,163,162);
	p(" Para %ctomos con muchos protones, esta notaci%cn puede ser muy larga, por lo que se utiliza una notaci%cn abreviada, que tiene en cuenta que las primeras subcapas son iguales a las de alg%cn gas noble. Por ejemplo, el f%csforo, difiere del arg%cn y ne%cn (1s2 2s2 2p6) %cnicamente por la presencia de la tercera capa. As%c, la configuraci%cn electr%cnica del f%csforo se puede escribir respecto de la del ne%cn como: [Ne] 3s2 3p3. Esta notaci%cn es %ctil si tenemos en cuenta que la mayor parte de las propiedades qu%cmicas de los elementos vienen determinadas por las capas m%cs externas.\n\n",160,162,162,163,162,162,162,163,161,162,162,162,162,162,163,161,160);
	p(" El orden en el que se escriben los orbitales viene dado por la estabilidad relativa de los orbitales, escribi%cndose primero aquellos que tienen menor energ%ca orbital. Esto significa que, aunque sigue unas pautas generales, se pueden producir excepciones. La mayor parte de los %ctomos siguen el orden dado por la regla de Madelung. As%c, de acuerdo con esta regla, la configuraci%cn electr%cnica del hierro se escribe como: [Ar] 4s2 3d6. Otra posible notaci%cn agrupa primero los orbitales con el mismo n%cmero cu%cntico n, de tal manera que la configuraci%cn del hierro se expresa como [Ar] 3d6 4s2 (agrupando el orbital 3d con los 3s y 3p que est%cn impl%ccitos en la configuraci%cn del arg%cn).\n\n",130,161,160,161,162,162,162,163,160,162,160,161,162,162);
	p(" El super%cndice 1 de los orbitales ocupados por un %cnico electr%cn no es obligatorio. Es bastante com%cn ver las letras de los orbitales escritas en letra it%clica o cursiva. Sin embargo, la Uni%cn Internacional de Qu%cmica Pura y Aplicada (IUPAC) recomienda utilizar letra normal, tal y como se realiza aqu%c.\n\n",161,163,162,163,160,162,161,161);
	
	system("pause");
	p("\n");
	
	p("- Estructura electr%cnica y tabla peri%cdica de los elementos:\n",162,162);
	p("------------------------------------------------------------\n\n");
	p(" - Bloques de la tabla peri%cdica de los elementos:\n\n",162);
	p(" La forma de la tabla peri%cdica de los elementos est%c %cntimamente relacionada con la configuraci%cn electr%cnica de los %ctomos de los elementos. Por ejemplo, todos los elementos del grupo 1 tienen una configuraci%cn de [E] ns1 (donde [E] es la configuraci%cn del gas inerte correspondiente), y tienen una gran semejanza en sus propiedades qu%cmicas. La capa electr%cnica m%cs externa se denomina 'capa de valencia' y (en una primera aproximaci%cn) determina las propiedades qu%cmicas. Conviene recordar que el hecho de que las propiedades qu%cmicas sean similares para los elementos de un grupo fue descubierto hace m%cs de un siglo, antes incluso de aparecer la idea de configuraci%cn electr%cnica. No est%c claro c%cmo explica la regla de Madelung (que m%cs bien describe) la tabla peri%cdica, ya que algunas propiedades (tales como el estado de oxidaci%cn +2 en la primera fila de los metales de transici%cn) ser%can diferentes con un orden de llenado de orbitales distinto. Por tanto las configuraciones electr%cnicas determinar%cn las propiedades de combinaci%cn qu%cmica.\n\n",162,160,161,162,162,160,162,162,161,162,160,162,161,161,160,162,162,160,162,160,162,162,162,161,162,160,162,161);
	
	system("pause");
	p("\n");
	
	p(" - Anomal%cas de configuraci%cn electr%cnica:\n\n",161,162,162);
	p(" Al desarrollar la configuraci%cn electr%cnica, encontramos una serie de excepciones. Por ejemplo, es m%cs estable llenar dos medios orbitales que completar uno y dejar el otro a uno o dos electrones de estar completado a la mitad. As%c, los metales del grupo 6 en vez de tener los orbitales externos completos y el orbital de un electr%cn de estar semi-completo, donar%cn un electr%cn del orbital, quedando ambos completos a la mitad: s1d5 en vez de s2d4. Igualmente, es m%cs estable rellenar los orbitales d completamente, por lo que los elementos del grupo 11 tender%cn a adoptar la configuraci%cn s1d10 en vez de s2d9.\n\n");
	
	system("pause");
	p("\n");
	
	p(" - Orbital o REEMPE:\n\n");
	p(" En qu%cmica se usa la expresi%cn REEMPE para designar el valor esperado de un operador densidad de estados de dos electrones. En otras palabras: la regi%cn donde existe mayor posibilidad de encontrar como m%cximo 2 electrones que se mueven en forma paralela y en sentidos contrarios. Su nombre proviene de Regi%cn de Espacio Energ%ctico de Manifestaci%cn Probabil%cstica del Electr%cn.\n\n",161,162,162,160,162,130,162,161,162);
	
	fprintf(archivo,"El modelo basado en la disposición de electrones en niveles sucesivos. Concepto de orbital. Los números cuánticos. Notación de los orbitales y configuración electrónica. Tabla periódica de los elementos y su interpretación electrónica:\n");
	fprintf(archivo,"===========================================================================================================================================================================================================================================\n\n");
	fprintf(archivo,"- Configuración electrónica:\n");
	fprintf(archivo,"----------------------------\n\n");
	fprintf(archivo,"En química, la configuración electrónica indica la manera en la cual los electrones se estructuran, comunican u organizan en un átomo de acuerdo con el modelo de capas electrónicas, en el cual las funciones de ondas del sistema se expresan como un átomo o atómicamente un producto de orbitales antisimetrizadas. La configuración electrónica es importante ya que determina las propiedades de combinación química de los átomos y por lo tanto su posición en la tabla periódica de los elementos.\n\n");
	fprintf(archivo," - Introducción:\n\n");
	fprintf(archivo," La disposición de los electrones en los átomos está sujeta a las reglas de la mecánica cuántica. En particular la configuración electrónica viene dada por una combinación de estados cuánticos que son solución de la ecuación de Schrödinger para dicho átomo.\n\n");
	fprintf(archivo," Una de las restricciones de la mecánica cuántica no explícitamente metida en la ecuación de Schrödinger es que cualquier conjunto de electrones en un mismo estado cuántico deben cumplir el principio de exclusión de Pauli por ser fermiones (partículas de espín semientero). Dicho principio implica que la función de onda total que describe dicho conjunto de electrones debe ser antisimétrica. Por lo tanto, en el momento en que un estado cuántico es ocupado por un electrón, el siguiente electrón debe ocupar un estado cuántico diferente.\n\n");
	fprintf(archivo," En los estados estacionarios de un átomo, la función de onda de un electrón en una aproximación no-relativista los estados que son función propia de la ecuación de Schrödinger es el hamiltoniano monoelectrónico correspondiente. Para el caso relativista hay que recurrir a la ecuación de Dirac. Las funciones propias obtenidas como solución de cualquiera de estas dos estaciones se denominan orbitales atómicos, por analogía con la imagen clásica de electrones orbitando alrededor del núcleo. Estos orbitales, en su expresión más básica, se pueden enumerar mediante cuatro números cuánticos: n, l, ml y ms. Obviamente, el principio de exclusión de Pauli implica que no puede haber dos electrones en un mismo átomo con los cuatro valores de los números cuánticos iguales (porque entonces ocuparían el mismo orbital y eso está excluido por el principio).\n\n");
	fprintf(archivo," De acuerdo con la mecánica cuántica, los electrones pueden pasar de un orbital atómico a otro ya sea emitiendo o absorbiendo un cuanto de energía, en forma de fotón. Esta transición de un orbital a otro con diferentes energías explican diversos fenómenos de emisión y absorción de radiación electromagnética por parte de los átomos.\n\n");
	fprintf(archivo," - Notación:\n\n");
	fprintf(archivo," Se utiliza en una notación estándar para describir las configuraciones electrónicas de átomos y moléculas. Para los átomos, la notación contiene la definición de los orbitales atómicos (en la forma n l, por ejemplo 1s, 2p, 3d, 4f) indicando el número de electrones asignado a cada orbital (o al conjunto de orbitales de la misma subcapa) como un superíndice. Por ejemplo, el hidrógeno tiene un electrón en el orbital s de la primera capa, de ahí que su configuración electrónica se escriba 1s1. El litio tiene dos electrones en la subcapa 1s y uno en la subcapa 2s (de mayor energía), de ahí que su configuración electrónica se escriba 1s2 2s1 (pronunciándose 'uno-ese-dos, dos-ese-uno'). Para el fósforo (número atómico 15), tenemos: 1s2 2s2 2p6 3s2 3p3.\n\n");
	fprintf(archivo," Para átomos con muchos protones, esta notación puede ser muy larga, por lo que se utiliza una notación abreviada, que tiene en cuenta que las primeras subcapas son iguales a las de algún gas noble. Por ejemplo, el fósforo, difiere del argón y neón (1s2 2s2 2p6) únicamente por la presencia de la tercera capa. Así, la configuración electrónica del fósforo se puede escribir respecto de la del neón como: [Ne] 3s2 3p3. Esta notación es útil si tenemos en cuenta que la mayor parte de las propiedades químicas de los elementos vienen determinadas por las capas más externas.\n\n");
	fprintf(archivo," El orden en el que se escriben los orbitales viene dado por la estabilidad relativa de los orbitales, escribiéndose primero aquellos que tienen menor energía orbital. Esto significa que, aunque sigue unas pautas generales, se pueden producir excepciones. La mayor parte de los átomos siguen el orden dado por la regla de Madelung. Así, de acuerdo con esta regla, la configuración electrónica del hierro se escribe como: [Ar] 4s2 3d6. Otra posible notación agrupa primero los orbitales con el mismo número cuántico n, de tal manera que la configuración del hierro se expresa como [Ar] 3d6 4s2 (agrupando el orbital 3d con los 3s y 3p que están implícitos en la configuración del argón).\n\n");
	fprintf(archivo," El superíndice 1 de los orbitales ocupados por un único electrón no es obligatorio. Es bastante común ver las letras de los orbitales escritas en letra itálica o cursiva. Sin embargo, la Unión Internacional de Química Pura y Aplicada (IUPAC) recomienda utilizar letra normal, tal y como se realiza aquí.\n\n");
	fprintf(archivo,"- Estructura electrónica y tabla periódica de los elementos:\n");
	fprintf(archivo,"------------------------------------------------------------\n\n");
	fprintf(archivo," - Bloques de la tabla periódica de los elementos:\n\n");
	fprintf(archivo," La forma de la tabla periódica de los elementos está íntimamente relacionada con la configuración electrónica de los átomos de los elementos. Por ejemplo, todos los elementos del grupo 1 tienen una configuración de [E] ns1 (donde [E] es la configuración del gas inerte correspondiente), y tienen una gran semejanza en sus propiedades químicas. La capa electrónica más externa se denomina 'capa de valencia' y (en una primera aproximación) determina las propiedades químicas. Conviene recordar que el hecho de que las propiedades químicas sean similares para los elementos de un grupo fue descubierto hace más de un siglo, antes incluso de aparecer la idea de configuración electrónica. No está claro cómo explica la regla de Madelung (que más bien describe) la tabla periódica, ya que algunas propiedades (tales como el estado de oxidación +2 en la primera fila de los metales de transición) serían diferentes con un orden de llenado de orbitales distinto. Por tanto las configuraciones electrónicas determinarán las propiedades de combinación química.\n\n");
	fprintf(archivo," - Anomalías de configuración electrónica:\n\n");
	fprintf(archivo," Al desarrollar la configuración electrónica, encontramos una serie de excepciones. Por ejemplo, es más estable llenar dos medios orbitales que completar uno y dejar el otro a uno o dos electrones de estar completado a la mitad. Así, los metales del grupo 6 en vez de tener los orbitales externos completos y el orbital de un electrón de estar semi-completo, donarán un electrón del orbital, quedando ambos completos a la mitad: s1d5 en vez de s2d4. Igualmente, es más estable rellenar los orbitales d completamente, por lo que los elementos del grupo 11 tenderán a adoptar la configuración s1d10 en vez de s2d9.\n\n");
	fprintf(archivo," - Orbital o REEMPE:\n\n");
	fprintf(archivo," En química se usa la expresión REEMPE para designar el valor esperado de un operador densidad de estados de dos electrones. En otras palabras: la región donde existe mayor posibilidad de encontrar como máximo 2 electrones que se mueven en forma paralela y en sentidos contrarios. Su nombre proviene de Región de Espacio Energético de Manifestación Probabilística del Electrón.\n\n");
	
	fclose(archivo);
}
